spring:
  datasource:
    username: sa
    password: 12345

  mail:
    username: anmom8910@gmail.com
    password: euat ysqv auav ffgs

security:
  jwt:
    secret: Wo/rLHAO919boG24AWVDwrd4GD1267ys9AEMFbyR1+0=
    expiration: 86400000

  oauth2:
    client:
      registration:
        google:
          client-secret: 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
