spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: { GOOGLE_CLIENT_ID }
            client-secret: { GOOGLE_CLIENT_SECRET }
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
session:
  store-type: jdbc
  jdbc:
    initialize-schema: always
  timeout: 30m
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
        http-only: true
        path: /
server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true